# .github/workflows/fetch-data.yml
name: Refresh Datasets

on:
  schedule:
    - cron: "0 */6 * * *"  # every 6 hours
  workflow_dispatch:       # manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run pipelines
        run: |
          poetry run python backend/pipelines/health_facilities.py
          poetry run python backend/pipelines/checkpoints.py
          poetry run python backend/pipelines/borders.py

      - name: Commit & push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add aid_dashboard_data
          git commit -m "Auto-update datasets [skip ci]" || echo "No changes to commit"
          git push